{application,firstapp,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{firstapp_app,1332}},
              {env,[]},
              {modules,[firstapp,firstapp_app,firstapp_client,firstapp_db,
                        firstapp_sup]}]}.
